a2lix_translation_form:
    locale_provider: default
    locales: [en, hu, de, ru, ua]
    default_locale: en
    required_locales: [en]
    templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"