a2lix_translation_form:
    locale_provider: default
    locales: '%app.locales%'
    default_locale: '%locale%'
    required_locales: ['%locale%']
    templating: "@A2lixTranslationForm/bootstrap_4_layout.html.twig"