easy_admin:
    site_name: '%env(APP_NAME)%'
    formats:
        datetime: 'd/m/Y H:i'
    list:
        title: '%%entity_label%% List'
    show:
        title: '%%entity_label%% (#%%entity_id%%)'
    design:
        brand_color: '#EAA83E'
        form_theme:   'vertical'
        color_scheme: 'dark'